<?php
namespace Dulcis\Dulcis\model\modeldata;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-03 at 06:02:54.
 */
class EntityAbstractTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var EntityAbstract
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EntityAbstract;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\EntityAbstract::__get
     * @todo   Implement test__get().
     */
    public function test__get()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\EntityAbstract::__set
     * @todo   Implement test__set().
     */
    public function test__set()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\EntityAbstract::toArray
     * @todo   Implement testToArray().
     */
    public function testToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
