<?php

namespace Dulcis\Dulcis\model\modeldata;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-03 at 05:55:55.
 */
class MemberTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Member
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Member;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\Member::setNumber
     * @todo   Implement testSetNumber().
     */
    public function testSetNumber() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\Member::getNumber
     * @todo   Implement testGetNumber().
     */
    public function testGetNumber() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\Member::setPassword
     * @todo   Implement testSetPassword().
     */
    public function testSetPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\Member::getPassword
     * @todo   Implement testGetPassword().
     */
    public function testGetPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\Member::setName
     * @todo   Implement testSetName().
     */
    public function testSetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\Member::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\Member::setEmail
     * @todo   Implement testSetEmail().
     */
    public function testSetEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\Member::getEmail
     * @todo   Implement testGetEmail().
     */
    public function testGetEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\Member::setPostnum
     * @todo   Implement testSetPostnum().
     */
    public function testSetPostnum() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\Member::getPostnum
     * @todo   Implement testGetPostnum().
     */
    public function testGetPostnum() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\Member::setAddress
     * @todo   Implement testSetAddress().
     */
    public function testSetAddress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\Member::getAddress
     * @todo   Implement testGetAddress().
     */
    public function testGetAddress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\Member::setTel
     * @todo   Implement testSetTel().
     */
    public function testSetTel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\Member::getTel
     * @todo   Implement testGetTel().
     */
    public function testGetTel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\Member::setPoint
     * @todo   Implement testSetPoint().
     */
    public function testSetPoint() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\Member::getPoint
     * @todo   Implement testGetPoint().
     */
    public function testGetPoint() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\Member::setCard
     * @todo   Implement testSetCard().
     */
    public function testSetCard() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dulcis\Dulcis\model\modeldata\Member::getCard
     * @todo   Implement testGetCard().
     */
    public function testGetCard() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
