<?php

namespace Dulcis\Dulcis\model\service\encode;

require_once(dirname(__FILE__).'/../../../../../bootstrap.php');

use PHPUnit_Framework_TestCase;
use Dulcis\Dulcis\model\service\encode\JsonEncoder;
use Dulcis\Dulcis\model\repository\factory\MemberUoWFactory;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-24 at 03:49:50.
 */
class JsonEncoderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var JsonEncoder
     */
    protected $object;
    protected $uow;
    protected $Member;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JsonEncoder;
        $this->uow = new MemberUoWFactory();
        $this->Member = $this->uow->create()->fetchByMname('tanaka');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Dulcis\Dulcis\model\service\encode\JsonEncoder::setData
     * @todo   Implement testSetData().
     */
    public function testSetData() {
        // Remove the following lines when you implement this test.
        assertArrayHasKey('name', $this->object->setData($this->Member->toArray()));
    }

    /**
     * @covers Dulcis\Dulcis\model\service\encode\JsonEncoder::encode
     * @todo   Implement testEncode().
     */
    public function testEncode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
